production:
  adapter: postgresql
  database: asset_tracker
  username: asset_tracker
  password: asset_tracker

development:
  adapter: postgresql
  database: asset_tracker
  username: asset_tracker
  password: asset_tracker

