#!/usr/bin/env ruby
=begin

Ensure each asset has the "base" role

@author Joel Heenan 31/01/2011

$HeadURL: http://svn.syd.int.threatmetrix.com/svn/tm/trunk/ops/asset_tracker/script/set_base_role $
$Id: set_base_role 27339 2011-01-31 01:17:31Z jheenan $

=end

require File.dirname(__FILE__) + '/../config/environment'
require 'rubygems'
require 'logger'
require 'pp'

def main
  base_role = Role.find( :first, :conditions => { :name => "base" } )
  Asset.find(:all).each do |asset|
    if not asset.role.include?(base_role)
      asset.role << base_role
      asset.save
    end
  end
end

main
